kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
data:
    ENVIRONMENT: "production"
    DB_USER: "ekseval"
    DB_NAME: "ekseval"
    DB_PORT: "5432"
    DB_HOST: ""
    DB_PASSWORD: ""